//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMedic.App.Resources {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMedic.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 网络急救箱 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在检查 的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查电脑连接 的本地化字符串。
        /// </summary>
        public static string Checkup_Stage1 {
            get {
                return ResourceManager.GetString("Checkup_Stage1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查网络地址和路由器 的本地化字符串。
        /// </summary>
        public static string Checkup_Stage2 {
            get {
                return ResourceManager.GetString("Checkup_Stage2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查网站名称解析 的本地化字符串。
        /// </summary>
        public static string Checkup_Stage3 {
            get {
                return ResourceManager.GetString("Checkup_Stage3", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查代理、VPN 和互联网 的本地化字符串。
        /// </summary>
        public static string Checkup_Stage4 {
            get {
                return ResourceManager.GetString("Checkup_Stage4", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查用户指定的目标 的本地化字符串。
        /// </summary>
        public static string Checkup_Stage5 {
            get {
                return ResourceManager.GetString("Checkup_Stage5", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 体检已取消。已有结果仍可查看。 的本地化字符串。
        /// </summary>
        public static string Checkup_Cancelled {
            get {
                return ResourceManager.GetString("Checkup_Cancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在体检… {0}/{1} 的本地化字符串。
        /// </summary>
        public static string Checkup_Progress {
            get {
                return ResourceManager.GetString("Checkup_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认执行 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已找到高可信原因 的本地化字符串。
        /// </summary>
        public static string Confidence_High {
            get {
                return ResourceManager.GetString("Confidence_High", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 证据不足，需要深度体检 的本地化字符串。
        /// </summary>
        public static string Confidence_Insufficient {
            get {
                return ResourceManager.GetString("Confidence_Insufficient", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 找到可能原因 的本地化字符串。
        /// </summary>
        public static string Confidence_Medium {
            get {
                return ResourceManager.GetString("Confidence_Medium", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 收起技术详情 的本地化字符串。
        /// </summary>
        public static string HideTechnicalDetails {
            get {
                return ResourceManager.GetString("HideTechnicalDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前网络状态摘要 的本地化字符串。
        /// </summary>
        public static string Home_ConnectionSummary {
            get {
                return ResourceManager.GetString("Home_ConnectionSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 开始网络体检 的本地化字符串。
        /// </summary>
        public static string Home_StartCheckup {
            get {
                return ResourceManager.GetString("Home_StartCheckup", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 只有一个应用/游戏打不开 的本地化字符串。
        /// </summary>
        public static string Home_Symptom_SingleAppDown {
            get {
                return ResourceManager.GetString("Home_Symptom_SingleAppDown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 什么都打不开 的本地化字符串。
        /// </summary>
        public static string Home_Symptom_NothingWorks {
            get {
                return ResourceManager.GetString("Home_Symptom_NothingWorks", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理或 VPN 关闭后不能上网 的本地化字符串。
        /// </summary>
        public static string Home_Symptom_ProxyVpnOff {
            get {
                return ResourceManager.GetString("Home_Symptom_ProxyVpnOff", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 只有部分网站打不开 的本地化字符串。
        /// </summary>
        public static string Home_Symptom_SomeSitesDown {
            get {
                return ResourceManager.GetString("Home_Symptom_SomeSitesDown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 我不确定 的本地化字符串。
        /// </summary>
        public static string Home_Symptom_Unsure {
            get {
                return ResourceManager.GetString("Home_Symptom_Unsure", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 你现在遇到哪种情况？ 的本地化字符串。
        /// </summary>
        public static string Home_SymptomPrompt {
            get {
                return ResourceManager.GetString("Home_SymptomPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 功能将在后续阶段实现。 的本地化字符串。
        /// </summary>
        public static string Placeholder_NotImplemented {
            get {
                return ResourceManager.GetString("Placeholder_NotImplemented", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已就绪 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安全修复 的本地化字符串。
        /// </summary>
        public static string SafeRepair {
            get {
                return ResourceManager.GetString("SafeRepair", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 展开技术详情 的本地化字符串。
        /// </summary>
        public static string ShowTechnicalDetails {
            get {
                return ResourceManager.GetString("ShowTechnicalDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 技术详情 的本地化字符串。
        /// </summary>
        public static string TechnicalDetails {
            get {
                return ResourceManager.GetString("TechnicalDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重新检查 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看处理方法 的本地化字符串。
        /// </summary>
        public static string ViewGuidance {
            get {
                return ResourceManager.GetString("ViewGuidance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认修复 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_Title {
            get {
                return ResourceManager.GetString("RepairConfirm_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将要修改 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_WhatWillChange {
            get {
                return ResourceManager.GetString("RepairConfirm_WhatWillChange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 原因 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_WhyNeeded {
            get {
                return ResourceManager.GetString("RepairConfirm_WhyNeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 是否会暂时断网 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_InterruptsNetwork {
            get {
                return ResourceManager.GetString("RepairConfirm_InterruptsNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 是否需要管理员权限 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_NeedsAdmin {
            get {
                return ResourceManager.GetString("RepairConfirm_NeedsAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 是否需要重启 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_NeedsReboot {
            get {
                return ResourceManager.GetString("RepairConfirm_NeedsReboot", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 能否自动撤销 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_Reversible {
            get {
                return ResourceManager.GetString("RepairConfirm_Reversible", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_Yes {
            get {
                return ResourceManager.GetString("RepairConfirm_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string RepairConfirm_No {
            get {
                return ResourceManager.GetString("RepairConfirm_No", resourceCulture);
            }
        }

        // --- Finding 文案（按 key 动态查找） ---

        // network_healthy
        public static string finding_network_healthy_title {
            get { return ResourceManager.GetString("finding.network_healthy.title", resourceCulture); }
        }
        public static string finding_network_healthy_explanation {
            get { return ResourceManager.GetString("finding.network_healthy.explanation", resourceCulture); }
        }
        public static string finding_network_healthy_summary {
            get { return ResourceManager.GetString("finding.network_healthy.summary", resourceCulture); }
        }
        public static string finding_network_healthy_guidance {
            get { return ResourceManager.GetString("finding.network_healthy.guidance", resourceCulture); }
        }

        // dead_local_proxy
        public static string finding_dead_local_proxy_title {
            get { return ResourceManager.GetString("finding.dead_local_proxy.title", resourceCulture); }
        }
        public static string finding_dead_local_proxy_explanation {
            get { return ResourceManager.GetString("finding.dead_local_proxy.explanation", resourceCulture); }
        }
        public static string finding_dead_local_proxy_summary {
            get { return ResourceManager.GetString("finding.dead_local_proxy.summary", resourceCulture); }
        }
        public static string finding_dead_local_proxy_guidance {
            get { return ResourceManager.GetString("finding.dead_local_proxy.guidance", resourceCulture); }
        }

        // winhttp_proxy_config
        public static string finding_winhttp_proxy_config_title {
            get { return ResourceManager.GetString("finding.winhttp_proxy_config.title", resourceCulture); }
        }
        public static string finding_winhttp_proxy_config_explanation {
            get { return ResourceManager.GetString("finding.winhttp_proxy_config.explanation", resourceCulture); }
        }
        public static string finding_winhttp_proxy_config_summary {
            get { return ResourceManager.GetString("finding.winhttp_proxy_config.summary", resourceCulture); }
        }
        public static string finding_winhttp_proxy_config_guidance {
            get { return ResourceManager.GetString("finding.winhttp_proxy_config.guidance", resourceCulture); }
        }

        // pac_unreachable
        public static string finding_pac_unreachable_title {
            get { return ResourceManager.GetString("finding.pac_unreachable.title", resourceCulture); }
        }
        public static string finding_pac_unreachable_explanation {
            get { return ResourceManager.GetString("finding.pac_unreachable.explanation", resourceCulture); }
        }
        public static string finding_pac_unreachable_summary {
            get { return ResourceManager.GetString("finding.pac_unreachable.summary", resourceCulture); }
        }
        public static string finding_pac_unreachable_guidance {
            get { return ResourceManager.GetString("finding.pac_unreachable.guidance", resourceCulture); }
        }

        // apipa_dhcp
        public static string finding_apipa_dhcp_title {
            get { return ResourceManager.GetString("finding.apipa_dhcp.title", resourceCulture); }
        }
        public static string finding_apipa_dhcp_explanation {
            get { return ResourceManager.GetString("finding.apipa_dhcp.explanation", resourceCulture); }
        }
        public static string finding_apipa_dhcp_summary {
            get { return ResourceManager.GetString("finding.apipa_dhcp.summary", resourceCulture); }
        }
        public static string finding_apipa_dhcp_guidance {
            get { return ResourceManager.GetString("finding.apipa_dhcp.guidance", resourceCulture); }
        }

        // dns_failure
        public static string finding_dns_failure_title {
            get { return ResourceManager.GetString("finding.dns_failure.title", resourceCulture); }
        }
        public static string finding_dns_failure_explanation {
            get { return ResourceManager.GetString("finding.dns_failure.explanation", resourceCulture); }
        }
        public static string finding_dns_failure_summary {
            get { return ResourceManager.GetString("finding.dns_failure.summary", resourceCulture); }
        }
        public static string finding_dns_failure_guidance {
            get { return ResourceManager.GetString("finding.dns_failure.guidance", resourceCulture); }
        }

        // ncsi_mismatch
        public static string finding_ncsi_mismatch_title {
            get { return ResourceManager.GetString("finding.ncsi_mismatch.title", resourceCulture); }
        }
        public static string finding_ncsi_mismatch_explanation {
            get { return ResourceManager.GetString("finding.ncsi_mismatch.explanation", resourceCulture); }
        }
        public static string finding_ncsi_mismatch_summary {
            get { return ResourceManager.GetString("finding.ncsi_mismatch.summary", resourceCulture); }
        }
        public static string finding_ncsi_mismatch_guidance {
            get { return ResourceManager.GetString("finding.ncsi_mismatch.guidance", resourceCulture); }
        }

        // captive_portal
        public static string finding_captive_portal_title {
            get { return ResourceManager.GetString("finding.captive_portal.title", resourceCulture); }
        }
        public static string finding_captive_portal_explanation {
            get { return ResourceManager.GetString("finding.captive_portal.explanation", resourceCulture); }
        }
        public static string finding_captive_portal_summary {
            get { return ResourceManager.GetString("finding.captive_portal.summary", resourceCulture); }
        }
        public static string finding_captive_portal_summary_possible {
            get { return ResourceManager.GetString("finding.captive_portal.summary_possible", resourceCulture); }
        }
        public static string finding_captive_portal_guidance {
            get { return ResourceManager.GetString("finding.captive_portal.guidance", resourceCulture); }
        }

        // target_unreachable
        public static string finding_target_unreachable_title {
            get { return ResourceManager.GetString("finding.target_unreachable.title", resourceCulture); }
        }
        public static string finding_target_unreachable_explanation {
            get { return ResourceManager.GetString("finding.target_unreachable.explanation", resourceCulture); }
        }
        public static string finding_target_unreachable_summary {
            get { return ResourceManager.GetString("finding.target_unreachable.summary", resourceCulture); }
        }
        public static string finding_target_unreachable_guidance {
            get { return ResourceManager.GetString("finding.target_unreachable.guidance", resourceCulture); }
        }

        // inconclusive
        public static string finding_inconclusive_title {
            get { return ResourceManager.GetString("finding.inconclusive.title", resourceCulture); }
        }
        public static string finding_inconclusive_explanation {
            get { return ResourceManager.GetString("finding.inconclusive.explanation", resourceCulture); }
        }
        public static string finding_inconclusive_summary {
            get { return ResourceManager.GetString("finding.inconclusive.summary", resourceCulture); }
        }
        public static string finding_inconclusive_guidance {
            get { return ResourceManager.GetString("finding.inconclusive.guidance", resourceCulture); }
        }

        /// <summary>
        ///   查找类似 处理方法 的本地化字符串。
        /// </summary>
        public static string GuidancePanel {
            get {
                return ResourceManager.GetString("GuidancePanel", resourceCulture);
            }
        }

        public static string GetString(string key) {
            return ResourceManager.GetString(key, resourceCulture) ?? key;
        }
    }
}
